### ISSUE TITLE
Update Lab tutorials to work with Python 3.x

### ISSUE THREAD

**Issue by virtualritz** [cloudshiftstrategies/flask_lambda_lab#2]
I get a bunch of errors that are all related to changes to between Python 2.x and 3.x.

Example:
```
$ python run.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 239-043-546
127.0.0.1 - - [09/Jul/2018 17:03:02] "GET /gallery HTTP/1.1" 200 -
127.0.0.1 - - [09/Jul/2018 17:03:08] "GET /upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/moeller/code/zappatest/app/__init__.py", line 100, in upload
    return render_template('upload.html', post = post)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/moeller/code/zappatest/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/moeller/code/zappatest/app/templates/upload.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/moeller/code/zappatest/app/templates/base.html", line 54, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/moeller/code/zappatest/app/templates/upload.html", line 14, in block "content"
    {% for parmName, value in post['fields'].iteritems() %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'iteritems'
```

**Comment by peterb154** [comment]
Ok, I have updated the entire lab to be be python2 and python3 compatible. The issues were around 

1. the python3 print function changed to require parentheses
2. the urllib module changed the way sub-modules (i.e. parse) are imported and 
3. the has_key() and iteritems() methods for lists are no longer available in python3. 

I also updated the [lab instructions](https://www.cloudshiftstrategies.com/flasklambdalab--lesson0.html) lesson0, step 6 to include instructions for using python3 in the lab.
